services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=my-rds-instance.c2g98h12z3.us-west-2.rds.amazonaws.com:3306 #defualt port
      - WORDPRESS_DB_USER=Wordpress-db
      - WORDPRESS_DB_PASSWORD=my_rds_db
      - WORDPRESS_DB_NAME=my_db
    volumes:
      - ./wp-content:/var/www/html/wp-content


# Runt he following commands
$ docker-compose up -d
$ docker run -d -p 80:80 --name my-wordpress-container my-wordpress-image


#Access your WordPress site: After the container is up and running, 
#you should be able to access your WordPress site by visiting http://localhost/ in your web browser.